version: "3"
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root-password
    volumes:
      - ./app/db/mysql_data:/var/lib/mysql
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec jets s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
